export const BASE_ROUTE = '/'
export const MANGA_ROUTE = '/manga'
export const COMMUNITY_ROUTE = '/comunidade'
export const GUIDE_ROUTE = '/guia'
export const LOGIN_ROUTE = '/login'
export const ANIME_ROUTE = '/anime'
export const UNIVERSE_ROUTE = '/universo'
export const CHAPTER_ROUTE = (id: string) => `/capitulo/${id}`
export const DASHBOARD_ROUTE = '/dashboard'
export const NEW_POST_ROUTE = '/novo-post'
export const NEW_CHAPTER_ROUTE = '/novo-capitulo'
